"""Builds the student-friendly PDF report with ReportLab."""
import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.config import REPORT_TITLE

_SEVERITY_COLOR = {
    "High": colors.HexColor("#c0392b"),
    "Medium": colors.HexColor("#d68910"),
    "Low": colors.HexColor("#7d8c1e"),
}


def generate_report(session, findings: list, quiz_attempts: list) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    body = styles["BodyText"]
    small = ParagraphStyle("small", parent=body, fontSize=9, leading=12)

    story = []
    story.append(Paragraph(REPORT_TITLE, styles["Title"]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(
        Paragraph(
            f"Session: <b>{session.name}</b> &nbsp;|&nbsp; Target: <b>{session.target_ip}</b> "
            f"&nbsp;|&nbsp; Generated: {session.created_at.strftime('%Y-%m-%d %H:%M UTC')}",
            body,
        )
    )
    story.append(Spacer(1, 0.6 * cm))

    story.append(Paragraph("Findings Summary", styles["Heading2"]))
    if not findings:
        story.append(Paragraph("No findings were recorded for this session.", body))
    else:
        table_data = [["Severity", "OWASP IoT", "Finding", "Evidence", "Mitigation"]]
        for f in findings:
            table_data.append(
                [
                    Paragraph(f.severity, small),
                    Paragraph(f.owasp_id, small),
                    Paragraph(f.title, small),
                    Paragraph(f.evidence, small),
                    Paragraph(f.mitigation, small),
                ]
            )
        table = Table(table_data, colWidths=[2 * cm, 2 * cm, 4 * cm, 5 * cm, 5 * cm], repeatRows=1)
        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f4f4")]),
        ]
        for row_idx, f in enumerate(findings, start=1):
            color = _SEVERITY_COLOR.get(f.severity, colors.black)
            style_commands.append(("TEXTCOLOR", (0, row_idx), (0, row_idx), color))
        table.setStyle(TableStyle(style_commands))
        story.append(table)

    story.append(Spacer(1, 0.8 * cm))

    if quiz_attempts:
        story.append(Paragraph("Learning Effectiveness (Pre/Post Quiz)", styles["Heading2"]))
        quiz_data = [["Phase", "Score", "Total", "Percentage"]]
        for q in quiz_attempts:
            pct = f"{(q.score / q.total * 100):.0f}%" if q.total else "n/a"
            quiz_data.append([q.phase.upper(), str(q.score), str(q.total), pct])
        quiz_table = Table(quiz_data, colWidths=[3 * cm, 3 * cm, 3 * cm, 3 * cm])
        quiz_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ]
            )
        )
        story.append(quiz_table)
        story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph("Disclaimer", styles["Heading2"]))
    story.append(
        Paragraph(
            "This report was generated by EduVAPT-IoT for educational purposes against an "
            "authorised lab target only. Findings and mitigation guidance are simplified for "
            "learning and are not a substitute for a professional security assessment.",
            body,
        )
    )

    doc.build(story)
    return buffer.getvalue()
